const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

const phoneList = [
  {
    company: "Iphone",
    phones: [
      {
        name: "Apple iPhone 16 Pro Max",
        released: "Released 2024, September 20",
        mermory: "256GB/512GB/1TB storage, no card slot",
        os: "iOS 18, up to iOS 18.3.1",
        display: '6.9"',
        resolution: "1320x2868 pixels",
        camera: "48",
        photoandvideo: "2160p",
        ram: "8",
        chipset: "Apple A18 Pro",
        battery: "4685",
        charging: "PD2.0",
        wat: "25W",
        img: "",
      },

      {
        name: "Apple iPhone 16 Plus",
        released: "Released 2024, September 20",
        mermory: "128GB/256GB/512GB storage, no card slot",
        os: "iOS 18, up to iOS 18.3.1",
        display: '6.7"',
        resolution: "1320x2868 pixels",
        camera: "48",
        photoandvideo: "2160p",
        ram: "8",
        chipset: "Apple A18",
        battery: "4674",
        charging: "PD2.0",
        wat: "25W",
        img: "",
      },
      {
        name: "Apple iPhone 13 Pro Max",
        released: "Released 2021, September 24",
        mermory: "128GB/256GB/1TB storage, no card slot",
        os: "iOS 15, up to iOS 18.3.1",
        display: '6.7"',
        resolution: "1284x2778 pixels",
        camera: "12",
        photoandvideo: "2160p",
        ram: "6",
        chipset: "Apple A15 Bionic",
        battery: "4352",
        charging: "PD2.0",
        wat: "15W",
        img: "",
      },
      {
        name: "Apple iPhone XS Max",
        released: "Released 2018, September 21",
        mermory: "64GB/256GB/512GB storage, no card slot",
        os: "iOS 12, up to iOS 18.3.1",
        display: '6.5"',
        resolution: "1242x2688 pixels",
        camera: "12",
        photoandvideo: "2160p",
        ram: "4",
        chipset: "Apple A12 Bionic",
        battery: "3174",
        charging: "15w",
        wat: "5W",
        img: "",
      },
    ],
  },
  {
    company: "Samsung",
    phones: [
      {
        name: "Samsung Galaxy S24 Ultra",
        released: "Released 2024, January 17",
        memory: "256GB/512GB/1TB storage, no card slot",
        os: "Android 14, One UI 6.1",
        display: '6.8"',
        resolution: "3120x1440 pixels",
        camera: "200MP",
        photoandvideo: "8K",
        ram: "12GB",
        chipset: "Qualcomm Snapdragon 8 Gen 3",
        battery: "5000mAh",
        charging: "45W",
        watt: "45W",
        img: "",
      },
      {
        name: "Samsung Galaxy S24+",
        released: "Released 2024, January 17",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, One UI 6.1",
        display: '6.7"',
        resolution: "3120x1440 pixels",
        camera: "50MP",
        photoandvideo: "8K",
        ram: "12GB",
        chipset: "Samsung Exynos 2400 or Qualcomm Snapdragon 8 Gen 3",
        battery: "4900mAh",
        charging: "45W",
        watt: "45W",
        img: "",
      },
      {
        name: "Samsung Galaxy S24",
        released: "Released 2024, January 17",
        memory: "128GB/256GB/512GB storage, no card slot",
        os: "Android 14, One UI 6.1",
        display: '6.2"',
        resolution: "2340x1080 pixels",
        camera: "50MP",
        photoandvideo: "8K",
        ram: "8GB/12GB",
        chipset: "Samsung Exynos 2400 or Qualcomm Snapdragon 8 Gen 3",
        battery: "4000mAh",
        charging: "25W",
        watt: "25W",
        img: "",
      },
      {
        name: "Samsung Galaxy S24 FE",
        released: "Released 2024, September 26",
        memory: "128GB/256GB/512GB storage, no card slot",
        os: "Android 14, One UI 6.1",
        display: '6.7"',
        resolution: "2340x1080 pixels",
        camera: "50MP",
        photoandvideo: "8K",
        ram: "8GB",
        chipset: "Samsung Exynos 2400e",
        battery: "4700mAh",
        charging: "25W",
        watt: "25W",
        img: "",
      },
      {
        name: "Samsung Galaxy A56 5G",
        released: "Released 2025, March 4",
        memory: "128GB/256GB storage, microSDXC slot",
        os: "Android 14, One UI 6.1",
        display: '6.7"',
        resolution: "2400x1080 pixels",
        camera: "50MP",
        photoandvideo: "4K",
        ram: "6GB/8GB",
        chipset: "Exynos 1580",
        battery: "5000mAh",
        charging: "45W",
        watt: "45W",
        img: "",
      },
      {
        name: "Samsung Galaxy A36 5G",
        released: "Released 2025, March 4",
        memory: "128GB/256GB storage, microSDXC slot",
        os: "Android 14, One UI 6.1",
        display: '6.7"',
        resolution: "2400x1080 pixels",
        camera: "50MP",
        photoandvideo: "4K",
        ram: "6GB/8GB",
        chipset: "Snapdragon 6 Gen3",
        battery: "5000mAh",
        charging: "45W",
        watt: "45W",
        img: "",
      },
    ],
  },
  {
    company: "Sony",
    phones: [
      {
        name: "Sony Xperia 1 V",
        released: "Released 2023, May 11",
        memory: "256GB/512GB storage, microSDXC",
        os: "Android 13, upgradable to Android 14",
        display: '6.5"',
        resolution: "1644x3840 pixels",
        camera: "48MP",
        photoandvideo: "4320p",
        ram: "12GB",
        chipset: "Snapdragon 8 Gen 2",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia 10 V",
        released: "Released 2023, July 01",
        memory: "128GB storage, microSDXC",
        os: "Android 13, upgradable to Android 14",
        display: '6.1"',
        resolution: "1080x2520 pixels",
        camera: "48MP",
        photoandvideo: "2160p",
        ram: "6GB/8GB",
        chipset: "Snapdragon 695 5G",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia 5 V",
        released: "Released 2023, September 01",
        memory: "128GB/256GB storage, microSDXC",
        os: "Android 13, upgradable to Android 14",
        display: '6.1"',
        resolution: "1080x2520 pixels",
        camera: "48MP",
        photoandvideo: "4320p",
        ram: "8GB",
        chipset: "Snapdragon 8 Gen 2",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia 1 IV",
        released: "Released 2022, June 11",
        memory: "256GB/512GB storage, microSDXC",
        os: "Android 12, upgradable to Android 14",
        display: '6.5"',
        resolution: "1644x3840 pixels",
        camera: "12MP",
        photoandvideo: "4320p",
        ram: "12GB",
        chipset: "Snapdragon 8 Gen 1",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia Pro-I",
        released: "Released 2021, December 10",
        memory: "512GB storage, microSDXC",
        os: "Android 11, upgradable to Android 14",
        display: '6.5"',
        resolution: "1644x3840 pixels",
        camera: "12MP",
        photoandvideo: "4320p",
        ram: "12GB",
        chipset: "Snapdragon 888 5G",
        battery: "4500mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia 10 IV",
        released: "Released 2022, June 11",
        memory: "128GB storage, microSDXC",
        os: "Android 12, upgradable to Android 14",
        display: '6.0"',
        resolution: "1080x2520 pixels",
        camera: "12MP",
        photoandvideo: "2160p",
        ram: "6GB",
        chipset: "Snapdragon 695 5G",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia 5 IV",
        released: "Released 2022, September 01",
        memory: "128GB/256GB storage, microSDXC",
        os: "Android 12, upgradable to Android 14",
        display: '6.1"',
        resolution: "1080x2520 pixels",
        camera: "12MP",
        photoandvideo: "4320p",
        ram: "8GB",
        chipset: "Snapdragon 8 Gen 1",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia 1 III",
        released: "Released 2021, August 25",
        memory: "256GB/512GB storage, microSDXC",
        os: "Android 11, upgradable to Android 14",
        display: '6.5"',
        resolution: "1644x3840 pixels",
        camera: "12MP",
        photoandvideo: "4320p",
        ram: "12GB",
        chipset: "Snapdragon 888 5G",
        battery: "4500mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Sony Xperia Pro",
        released: "Released 2021, January 27",
        memory: "512GB storage, microSDXC",
        os: "Android 10, upgradable to Android 14",
        display: '6.5"',
        resolution: "1644x3840 pixels",
        camera: "12MP",
        photoandvideo: "4320p",
        ram: "12GB",
        chipset: "Snapdragon 865 5G",
        battery: "4000mAh",
        charging: "Fast charging",
        watt: "21W",
        img: "",
      },
      {
        name: "Sony Xperia 10 III",
        released: "Released 2021, June 11",
        memory: "128GB storage, microSDXC",
        os: "Android 11, upgradable to Android 14",
        display: '6.0"',
        resolution: "1080x2520 pixels",
        camera: "12MP",
        photoandvideo: "2160p",
        ram: "6GB",
        chipset: "Snapdragon 690 5G",
        battery: "4500mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
    ],
  },
  {
    company: "Xiaomi",
    phones: [
      {
        name: "Xiaomi 15 Ultra",
        released: "Released 2025, February 28",
        memory: "256GB/512GB/1TB storage, no card slot",
        os: "Android 14, MIUI 16",
        display: '6.73"',
        resolution: "1440x3200 pixels",
        camera: "50MP",
        photoandvideo: "4320p",
        ram: "12GB/16GB",
        chipset: "Snapdragon 8 Elite",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "90W",
        img: "",
      },
      {
        name: "Xiaomi 15",
        released: "Released 2024, October 29",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 15, HyperOS 2",
        display: '6.36"',
        resolution: "1200x2670 pixels",
        camera: "50MP",
        photoandvideo: "4320p",
        ram: "12GB/16GB",
        chipset: "Snapdragon 8 Elite",
        battery: "5400mAh",
        charging: "Fast charging",
        watt: "90W",
        img: "",
      },
      {
        name: "Xiaomi 15 Pro",
        released: "Released 2024, October 29",
        memory: "256GB/512GB/1TB storage, no card slot",
        os: "Android 15, HyperOS 2",
        display: '6.73"',
        resolution: "1440x3200 pixels",
        camera: "50MP",
        photoandvideo: "4320p",
        ram: "12GB/16GB",
        chipset: "Snapdragon 8 Elite",
        battery: "6100mAh",
        charging: "Fast charging",
        watt: "90W",
        img: "",
      },
      {
        name: "Xiaomi Mix Flip",
        released: "Released 2024, October 15",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, MIUI 15",
        display: '6.86"',
        resolution: "1080x2520 pixels",
        camera: "50MP",
        photoandvideo: "4320p",
        ram: "12GB",
        chipset: "Snapdragon 8 Gen 3",
        battery: "4780mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Xiaomi Mix Fold 4",
        released: "Released 2024, August 16",
        memory: "256GB/512GB/1TB storage, no card slot",
        os: "Android 14, MIUI 15",
        display: '8.02"',
        resolution: "1914x2160 pixels",
        camera: "50MP",
        photoandvideo: "4320p",
        ram: "12GB/16GB",
        chipset: "Snapdragon 8 Gen 3",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Xiaomi 14T Pro",
        released: "Released 2024, July 20",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, MIUI 15",
        display: '6.67"',
        resolution: "1220x2712 pixels",
        camera: "200MP",
        photoandvideo: "4320p",
        ram: "12GB",
        chipset: "Snapdragon 8 Gen 2",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "120W",
        img: "",
      },
      {
        name: "Xiaomi 14T",
        released: "Released 2024, July 20",
        memory: "128GB/256GB storage, no card slot",
        os: "Android 14, MIUI 15",
        display: '6.67"',
        resolution: "1220x2712 pixels",
        camera: "108MP",
        photoandvideo: "4320p",
        ram: "8GB",
        chipset: "Snapdragon 8 Gen 2",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "120W",
        img: "",
      },
      {
        name: "Xiaomi 14 Civi",
        released: "Released 2024, May 10",
        memory: "128GB/256GB storage, no card slot",
        os: "Android 14, MIUI 15",
        display: '6.55"',
        resolution: "1080x2400 pixels",
        camera: "50MP",
        photoandvideo: "4320p",
        ram: "8GB/12GB",
        chipset: "Snapdragon 7 Gen 2",
        battery: "4500mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Xiaomi 14 Lite",
        released: "Released 2024, March 25",
        memory: "128GB/256GB storage, microSDXC",
        os: "Android 14, MIUI 15",
        display: '6.55"',
        resolution: "1080x2400 pixels",
        camera: "64MP",
        photoandvideo: "2160p",
        ram: "6GB/8GB",
        chipset: "Snapdragon 7 Gen 1",
        battery: "4500mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Xiaomi 14",
        released: "Released 2023, December 31",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 13, MIUI 14",
        display: '6.36"',
        resolution: "1200x2670 pixels",
        camera: "50MP",
        photoandvideo: "4320p",
        ram: "8GB/12GB",
        chipset: "Snapdragon 8 Gen 2",
        battery: "4500mAh",
        charging: "Fast charging",
        watt: "90W",
        img: "",
      },
    ],
  },
  {
    company: "Oppo",
    phones: [
      {
        name: "Oppo Find N5",
        released: "Released 2025, February 28",
        memory: "512GB storage, no card slot",
        os: "Android 14, ColorOS 14",
        display: '7.1"',
        resolution: "1792x1920 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "16GB",
        chipset: "Qualcomm Snapdragon 8 Elite",
        battery: "5600mAh",
        charging: "Fast charging",
        watt: "80W",
        img: "",
      },
      {
        name: "Oppo Reno13 Pro",
        released: "Released 2024, November 15",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, ColorOS 14",
        display: '6.74"',
        resolution: "2772x1270 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "16GB",
        chipset: "MediaTek Dimensity 8350",
        battery: "5800mAh",
        charging: "Fast charging",
        watt: "80W",
        img: "",
      },
      {
        name: "Oppo Reno13",
        released: "Released 2024, November 15",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, ColorOS 14",
        display: '6.59"',
        resolution: "2760x1256 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "12GB/16GB",
        chipset: "MediaTek Dimensity 8350",
        battery: "5600mAh",
        charging: "Fast charging",
        watt: "80W",
        img: "",
      },
      {
        name: "Oppo Reno13 F",
        released: "Released 2025, January 10",
        memory: "256GB/512GB storage, microSDXC",
        os: "Android 14, ColorOS 14",
        display: '6.67"',
        resolution: "2400x1080 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "8GB",
        chipset: "MediaTek Helio G100",
        battery: "5800mAh",
        charging: "Fast charging",
        watt: "45W",
        img: "",
      },
      {
        name: "Oppo Reno12 Pro",
        released: "Released 2024, August 27",
        memory: "256GB storage, no card slot",
        os: "Android 14, ColorOS 13",
        display: '6.7"',
        resolution: "2412x1080 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "12GB",
        chipset: "MediaTek Dimensity 7050",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Oppo Reno12",
        released: "Released 2024, August 27",
        memory: "256GB storage, no card slot",
        os: "Android 14, ColorOS 13",
        display: '6.7"',
        resolution: "2412x1080 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "8GB",
        chipset: "MediaTek Dimensity 7050",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Oppo Reno11 Pro",
        released: "Released 2024, January 15",
        memory: "256GB storage, no card slot",
        os: "Android 13, ColorOS 13",
        display: '6.74"',
        resolution: "2772x1270 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "12GB",
        chipset: "MediaTek Dimensity 8200",
        battery: "4600mAh",
        charging: "Fast charging",
        watt: "80W",
        img: "",
      },
      {
        name: "Oppo Reno11",
        released: "Released 2024, January 15",
        memory: "128GB/256GB storage, no card slot",
        os: "Android 13, ColorOS 13",
        display: '6.7"',
        resolution: "2412x1080 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "8GB/12GB",
        chipset: "MediaTek Dimensity 7050",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Oppo Reno11 F",
        released: "Released 2024, February 20",
        memory: "256GB storage, microSDXC",
        os: "Android 13, ColorOS 13",
        display: '6.67"',
        resolution: "2400x1080 pixels",
        camera: "64MP",
        photoandvideo: "2160p",
        ram: "8GB",
        chipset: "MediaTek Dimensity 7050",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "67W",
        img: "",
      },
      {
        name: "Oppo Find X8 Pro",
        released: "Released 2024, March 10",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, ColorOS 14",
        display: '6.82"',
        resolution: "1440x3168 pixels",
        camera: "50MP",
        photoandvideo: "2160p",
        ram: "12GB/16GB",
        chipset: "Qualcomm Snapdragon 8 Gen 3",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "80W",
        img: "",
      },
    ],
  },
  {
    company: "Asus",
    phones: [
      {
        name: "Asus Zenfone 12 Ultra",
        released: "Released 2025, March 5",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, ZenUI 12",
        display: '6.8"',
        resolution: "3200x1440 pixels",
        camera: "108MP",
        photoandvideo: "8K",
        ram: "12GB/16GB",
        chipset: "Qualcomm Snapdragon 8 Gen 3",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus ROG Phone 9 Pro",
        released: "Released 2025, January 20",
        memory: "512GB/1TB storage, no card slot",
        os: "Android 14, ROG UI",
        display: '6.78"',
        resolution: "2448x1080 pixels",
        camera: "64MP",
        photoandvideo: "8K",
        ram: "16GB/24GB",
        chipset: "Qualcomm Snapdragon 8 Elite",
        battery: "6000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus ROG Phone 9",
        released: "Released 2025, January 20",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 14, ROG UI",
        display: '6.78"',
        resolution: "2448x1080 pixels",
        camera: "64MP",
        photoandvideo: "8K",
        ram: "12GB/16GB",
        chipset: "Qualcomm Snapdragon 8 Elite",
        battery: "6000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus Zenfone 11 Ultra",
        released: "Released 2024, August 15",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 13, ZenUI 11",
        display: '6.8"',
        resolution: "3200x1440 pixels",
        camera: "108MP",
        photoandvideo: "8K",
        ram: "12GB/16GB",
        chipset: "Qualcomm Snapdragon 8 Gen 2",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus ROG Phone 8 Pro",
        released: "Released 2024, March 10",
        memory: "512GB/1TB storage, no card slot",
        os: "Android 13, ROG UI",
        display: '6.78"',
        resolution: "2448x1080 pixels",
        camera: "64MP",
        photoandvideo: "8K",
        ram: "16GB/24GB",
        chipset: "Qualcomm Snapdragon 8 Gen 2",
        battery: "6000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus ROG Phone 8",
        released: "Released 2024, March 10",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 13, ROG UI",
        display: '6.78"',
        resolution: "2448x1080 pixels",
        camera: "64MP",
        photoandvideo: "8K",
        ram: "12GB/16GB",
        chipset: "Qualcomm Snapdragon 8 Gen 2",
        battery: "6000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus Zenfone 10",
        released: "Released 2023, October 5",
        memory: "128GB/256GB storage, microSDXC",
        os: "Android 13, ZenUI 10",
        display: '6.3"',
        resolution: "2400x1080 pixels",
        camera: "50MP",
        photoandvideo: "8K",
        ram: "8GB/12GB",
        chipset: "Qualcomm Snapdragon 8+ Gen 1",
        battery: "4300mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
      {
        name: "Asus ROG Phone 7 Ultimate",
        released: "Released 2023, April 13",
        memory: "512GB storage, no card slot",
        os: "Android 13, ROG UI",
        display: '6.78"',
        resolution: "2448x1080 pixels",
        camera: "64MP",
        photoandvideo: "8K",
        ram: "16GB",
        chipset: "Qualcomm Snapdragon 8 Gen 2",
        battery: "6000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus ROG Phone 7",
        released: "Released 2023, April 13",
        memory: "256GB/512GB storage, no card slot",
        os: "Android 13, ROG UI",
        display: '6.78"',
        resolution: "2448x1080 pixels",
        camera: "64MP",
        photoandvideo: "8K",
        ram: "12GB/16GB",
        chipset: "Qualcomm Snapdragon 8 Gen 2",
        battery: "6000mAh",
        charging: "Fast charging",
        watt: "65W",
        img: "",
      },
      {
        name: "Asus Zenfone 9",
        released: "Released 2022, September 15",
        memory: "128GB/256GB storage, no card slot",
        os: "Android 12, upgradable to Android 14",
        display: '5.9"',
        resolution: "2400x1080 pixels",
        camera: "50MP",
        photoandvideo: "8K",
        ram: "8GB/16GB",
        chipset: "Qualcomm Snapdragon 8+ Gen 1",
        battery: "4300mAh",
        charging: "Fast charging",
        watt: "30W",
        img: "",
      },
    ],
  },
  {
    company: "Infinix",
    phones: [
      {
        name: "Infinix Note 50 Pro 4G",
        released: "Expected 2025",
        memory: "128GB/256GB storage, microSDXC",
        os: "Android 14, XOS 10.6",
        display: '6.9"',
        resolution: "1080x2460 pixels",
        camera: "108MP",
        photoandvideo: "4K",
        ram: "8GB",
        chipset: "MediaTek Helio G99",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "33W",
        img: "",
      },
      {
        name: "Infinix Zero Flip",
        released: "Expected 2025",
        memory: "256GB storage, no card slot",
        os: "Android 14, XOS 10.6",
        display: '6.8"',
        resolution: "1080x2400 pixels",
        camera: "50MP",
        photoandvideo: "4K",
        ram: "12GB",
        chipset: "MediaTek Dimensity 1200",
        battery: "4000mAh",
        charging: "Fast charging",
        watt: "44W",
        img: "",
      },
      {
        name: "Infinix Note 40 Pro+",
        released: "Expected 2025",
        memory: "128GB/256GB storage, microSDXC",
        os: "Android 14, XOS 10.6",
        display: '6.95"',
        resolution: "1080x2460 pixels",
        camera: "108MP",
        photoandvideo: "4K",
        ram: "8GB",
        chipset: "MediaTek Helio G99",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "33W",
        img: "",
      },
      {
        name: "Infinix Zero 40 5G",
        released: "Expected 2025",
        memory: "256GB storage, no card slot",
        os: "Android 14, XOS 10.6",
        display: '6.8"',
        resolution: "1080x2400 pixels",
        camera: "50MP",
        photoandvideo: "4K",
        ram: "12GB",
        chipset: "MediaTek Dimensity 1200",
        battery: "4500mAh",
        charging: "Fast charging",
        watt: "44W",
        img: "",
      },
      {
        name: "Infinix Hot 50 Pro 4G",
        released: "Expected 2025",
        memory: "128GB storage, microSDXC",
        os: "Android 14, XOS 10.6",
        display: '6.82"',
        resolution: "720x1640 pixels",
        camera: "50MP",
        photoandvideo: "1080p",
        ram: "6GB",
        chipset: "MediaTek Helio G85",
        battery: "6000mAh",
        charging: "Fast charging",
        watt: "18W",
        img: "",
      },
      {
        name: "Infinix Smart 9 HD",
        released: "Expected 2025",
        memory: "64GB storage, microSDXC",
        os: "Android 14 (Go edition), XOS 10.6",
        display: '6.6"',
        resolution: "720x1612 pixels",
        camera: "8MP",
        photoandvideo: "1080p",
        ram: "2GB",
        chipset: "Unisoc SC9863A1",
        battery: "5000mAh",
        charging: "Standard charging",
        watt: "10W",
        img: "",
      },
      {
        name: "Infinix Hot 50i",
        released: "Expected 2025",
        memory: "64GB storage, microSDXC",
        os: "Android 14 (Go edition), XOS 10.6",
        display: '6.52"',
        resolution: "720x1600 pixels",
        camera: "8MP",
        photoandvideo: "1080p",
        ram: "2GB",
        chipset: "Unisoc SC7731E",
        battery: "5000mAh",
        charging: "Standard charging",
        watt: "10W",
        img: "",
      },
      {
        name: "Infinix Zero 30 4G",
        released: "2024, September",
        memory: "256GB storage, microSDXC",
        os: "Android 13, XOS 10.6",
        display: '6.78"',
        resolution: "1080x2400 pixels",
        camera: "108MP",
        photoandvideo: "4K",
        ram: "8GB",
        chipset: "MediaTek Helio G99",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "33W",
        img: "",
      },
      {
        name: "Infinix GT 10 Pro",
        released: "2024, August",
        memory: "256GB storage, microSDXC",
        os: "Android 13, XOS 10.6",
        display: '6.67"',
        resolution: "1080x2400 pixels",
        camera: "108MP",
        photoandvideo: "4K",
        ram: "8GB",
        chipset: "MediaTek Dimensity 8050",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "45W",
        img: "",
      },
      {
        name: "Infinix Note 30 VIP",
        released: "2024, June",
        memory: "256GB storage, microSDXC",
        os: "Android 13, XOS 10.6",
        display: '6.67"',
        resolution: "1080x2400 pixels",
        camera: "108MP",
        photoandvideo: "4K",
        ram: "12GB",
        chipset: "MediaTek Dimensity 8050",
        battery: "5000mAh",
        charging: "Fast charging",
        watt: "68W",
        img: "",
      },
    ],
  },
];

// API route to get all phone data
app.get("/api/phones", (req, res) => {
  res.json(phoneList);
});

// API route to get phones by company
app.get("/api/phones/:company", (req, res) => {
  const company = req.params.company.toLowerCase();
  const result = phoneList.find(
    (item) => item.company.toLowerCase() === company
  );
  if (result) {
    res.json(result);
  } else {
    res.status(404).json({ message: "Company not found" });
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
